spring:
  application:
    name: Spring Boot Starter
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_stater
    username: rimnaarith
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/springboot_stater
    user: rimnaarith
    password: mypassword

# Spring Doc properties
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8222

# Custom properties
application:
  file:
    upload-dir: ./uploads
  security:
    secret: 379fab244599ccbb5a42a6138bf28b147d60992f2b2fa99e3c05bbe090bd6535
